GET http://localhost:8000/users

### Request Headers
POST http://localhost:8000/users
Content-Type: application/json

{
  "name": "John Doe",
  "password": "password123",
  "email": "john.doe@example.com",
  "restaurentname": "Doe's Diner",
  "branchname": "Main Branch",
  "branchaddress": "123 Main St",
  "phonenumber": "123-456-7890",
  "id": "user-123",
  "country": "USA"
}

###

POST http://localhost:8000/login
Content-Type: application/json

{
  "email": "x@gmail.com",
  "password": "mohan5454I@"
}