GET http://localhost:8000/restaurant/4fffa99e-6658-487b-8f82-0cb811e14bdd

### Request Headers
POST http://localhost:8000/restaurant
Content-Type: application/json

{
  "name": "Mohan",
  "password": "mohan5454I@",
  "email": "mohan@example.com",
  "restaurentname": "Guntur Gongura",
  "branchname": "Kurnool Branch",
  "branchaddress": "123 Main St",
  "phonenumber": "9848226768",
  "id": "user-1234",
  "country": "India"
}

###

POST http://localhost:8000/restaurant_details/addArea
Content-Type: application/json

{
  "area_id": "area-1234-2",
  "area_name": "Main Dining Area",
  "restaurant_id": "user-1234"
}

###

POST http://localhost:8000/restaurant_details/addTable
Content-Type: application/json

{
  "table_id": "table-1234-2-3",
  "table_name": "F01",
  "table_capacity": 3,
  "table_status": "Active",
  "area_id": "area-1234-2",
  "restaurant_id": "user-1234"
}

###
POST http://localhost:8000/restaurant_details/addMenuCategory
Content-Type: application/json

{
  "menu_category_id": "category-1234",
  "menu_category_name": "Tiffins",
  "restaurant_id": "user-1234"
}

###
POST http://localhost:8000/restaurant_details/addMenuItems
Content-Type: application/json

{
  "item_id": "item-1234",
  "item_name": "Broune",
  "item_dec": "made with chocolate",
  "item_price": "800",
  "item_menu_category_id": "category-1234",
  "item_category": "Veg",
  "item_availabiliy": "true",
  "item_preparation_time": "20",
  "restaurant_id": "user-1234"
}